[package]
name = "mio_httpc"
version = "0.6.15"
authors = ["sergej jurecko <sergej.jurecko@gmail.com>"]
description = "mio_httpc is a fully async and sync http client running on top of mio only. "
repository = "https://github.com/SergejJurecko/mio_httpc"
readme = "README.md"
keywords = ["mio", "http", "client", "async", "websocket"]
categories = ["network-programming"]
license = "MIT/Apache-2.0"
documentation = "http://docs.rs/mio_httpc"
homepage = "https://github.com/SergejJurecko/mio_httpc"
build = "build.rs"

[features]
# Default does not work.
default = []
native = ["native-tls"]
rtls = ["webpki-roots", "webpki", "rustls"]

[dependencies]
mio = "0.6"
httparse = "1"
byteorder = "1"
libc = "0.2"
fnv = "1"
rand = "0.5"
itoa = "0.4"
data-encoding = "2.1"
failure = "0.1"
smallvec = "0.6"
md5 = "0.3"
pest = "1"
pest_derive = "1"
libflate = "0.1"
slab = "0.4"
percent-encoding = "1"
url = "1"


webpki = {version = "^0.18.0-alpha", optional = true}
webpki-roots = {version = "0.14", optional = true}
rustls = { version = "0.12", features = ["dangerous_configuration"], optional = true}
openssl      = { version = "0.10.*", optional = true, features = ["v102", "v110"] }
native-tls   = { version = "0.2", optional = true}

[dev-dependencies]
matches = "0.1"
